name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
        service_account: '${{ secrets.APPENGINE_DEPLOY_SA_EMAIL }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          credentials: ${{ secrets.gcp_credentials }}